spring.application.name=flyway-migrations

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_flyway
spring.datasource.username=user
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# validon klasen modelin ne java me tabelen qe ekzituese ne DB
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/docs

spring.jwt.secret=9184aaabf55dc8a0fb13dc1bcaed602ca4c1ca25d6c36913edb048f4e63a2490
spring.jwt.expiration=86400000